FROM httpd:latest

# typically, this is set by the environment file as part of docker compose
# this is here so that it is clear what variables this file needs
ARG BASE_API_URL
ENV BASE_API_URL $BASE_API_URL

RUN apt-get update \
    && apt-get -y install \
        git

RUN git clone https://github.com/NCAR/music-box-interactive-static
RUN cd music-box-interactive-static

RUN echo $BASE_API_URL
# set the base url used by the web files
RUN sed -i "1 s/^.*$/var globalBaseAPIUrl = \"$BASE_API_URL\";/" music-box-interactive-static/js/api.js

RUN cp -r music-box-interactive-static/* /usr/local/apache2/htdocs/
