FROM ghcr.io/ncar/music-box:release

RUN dnf -y update \
    && dnf -y install \
        python3-pandas \
    && dnf clean all

# copy the interactive server code
COPY . /music-box-interactive/

# python modules needed in scripts
RUN pip3 install -r /music-box-interactive/requirements.txt

ENV MUSIC_BOX_BUILD_DIR=/music-box/build

# Start the model runner on entry
CMD ["python3", "/music-box-interactive/interactive/rabbit_mq_model_runner.py"]
