apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: hub.k8s.ucar.edu/musicbox/frontend
  newName: hub.k8s.ucar.edu/musicbox/frontend
  newTag: "2798103"

namePrefix: devel-

resources:
- ../../base

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/instance: devel
    app.kubernetes.io/name: musicbox
