FROM fedora:latest

RUN dnf -y update \
    && dnf -y install \
        gcc \
        gcc-c++ \
        python3 \
        python3-devel \
        python3-pip \
    && dnf clean all

RUN pip3 install poetry

COPY . /music-box-interactive/
WORKDIR /music-box-interactive

RUN poetry install

CMD ["poetry", "run", "python3", "/music-box-interactive/interactive/rabbit_mq_model_status_listener.py"]