# Generated by Django 4.2 on 2023-04-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRun',
            fields=[
                ('uid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('config_checksum', models.CharField(max_length=50)),
                ('is_running', models.BooleanField(default=False)),
                ('results', models.JSONField(default=dict)),
                ('should_cache', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionUser',
            fields=[
                ('uid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('config_files', models.JSONField(default=dict)),
                ('binary_files', models.JSONField(default=dict)),
                ('should_cache', models.BooleanField(default=False)),
                ('config_checksum', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
